name: example
description: Example app for managed package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

isar_version: &isar_version 3.0.2

dependencies:
  flutter:
    sdk: flutter
  managed:
    path: ../
  cupertino_icons: ^1.0.2
  oxidized: ^5.2.0
  go_router: ^5.0.5
  flutter_portal: ^1.1.1
  lumberdash: ^3.0.0
  colorize_lumberdash: ^3.0.0
  mobx: ^2.1.0
  flutter_mobx: ^2.0.6+4
  isar: *isar_version
  isar_flutter_libs: *isar_version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: *isar_version
  build_runner: any

flutter:
  uses-material-design: true